def rep_dict_function():
#=====================================================================================
#Generate a dictionary containing strings to be added in place of strngs to be replaced
#=====================================================================================
    rep_dict = {}

# To add new replaced and replacing strings -> preserve syntax
#
# replaced_string = "string_to_replace"
# replacing_list = ["replacing_string_line_1",
#                   replacing_string_line_2"]
# rep_dict[replaced_string] = replacing_list
#
# -> new lines are new strings in replacing list


#=====================================================================================
#Pneumatic retraction (Turn pressure off and turn discharge on)
#=====================================================================================
    replaced_ret =  "F36000 ;"

    replacing_ret = ["F360.000 ;" ,
                     "",
                     ";Retraction (Release pressure)",
                     "M106 S0;" ,
                     "M106 P3;",
                     "",
                     ";Non-Printing movements"]

    rep_dict[replaced_ret] = replacing_ret


#=====================================================================================
# Pneumatic unretraction (Turn pressure on and turn discharge off)
#=====================================================================================
    replaced_unretract = "F72000 ;"

    replacing_unretract = ["F720.000 ;" ,
                           "",
                           ";De-retraction (Apply pressure)",
                           "M107 P3;" ,
                           "M106 S255;",
                           "",
                           ";Printing movements"]

    rep_dict[replaced_unretract] = replacing_unretract


#=====================================================================================
#Heading
#=====================================================================================
    replaced_heading = "; generated by PrusaSlicer"

    replacing_heading = [";Generated by PrusaSlicer",
                         ";Converted for use on Chimera MK2 via Chimera GCode_Generator",
                         "",
                         ";Developed @+Lab, Politecnico di Milano"]

    rep_dict[replaced_heading] = replacing_heading

    return rep_dict
